version: '3'

services:
  node:
    image: node:alpine
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    working_dir: /home/node/app
    user: node
    command: "tail -f /dev/null"
