version: '3'

services:
  node:
    image: node:alpine
    ports:
      - '3000:3000'
    volumes:
      - ./:/srv/app
    working_dir: /srv/app
    user: node
    command: sh -c "npm i && npm run dev"